Fix/create item button
DEIPworld/casimir-sandbox-portal pull request #22
Opened 2022-06-17 12:28 UTC by ShmidtAlex

2022-06-17 12:32 UTC, d-tsaruk commented on src/mixins/roles.js
> +      if (!id && !isDraft) {
ты только что объявил id. оно всегда undefined

2022-06-17 12:33 UTC, d-tsaruk commented on src/mixins/roles.js
> +export const rolesFactory = (teamIdPath, isDraft) => ({
isDraft это функция? если же это все таки флаг то он не должен начнаться с глагола.
ибо звучит как is draft? как вопрос

тут проще тогда назвать как draftItem, draft, draftInstance и т д

2022-06-17 12:34 UTC, elena-vlasova commented on src/mixins/roles.js
> +export const rolesFactory = (teamIdPath, isDraft) => ({
Что такое isDraft?

2022-06-17 12:34 UTC, elena-vlasova commented on src/mixins/roles.js
> +        id = this.project.issuedByTeam
Метод $$isTeamAdmin не подразумевает обязательное наличие project в this

2022-06-17 12:35 UTC, elena-vlasova commented on src/mixins/roles.js
> +export const rolesFactory = (teamIdPath, isDraft) => ({
draft тоже не очень показывает, что там содержится boolean значение, а кажется, что там лежит сущность драфта

2022-06-17 12:42 UTC, d-tsaruk commented on src/mixins/roles.js
> +export const rolesFactory = (teamIdPath, isDraft) => ({
в английском с глагола начинаются вопросы

2022-06-17 12:44 UTC, d-tsaruk commented on src/mixins/roles.js
> +export const rolesFactory = (teamIdPath, isDraft) => ({
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/45588750/174300735-e7d0cfb9-87d9-4484-94e9-248332a959d3.png">

2022-06-17 12:53 UTC, elena-vlasova commented on src/mixins/roles.js
> +export const rolesFactory = (teamIdPath, isDraft) => ({
Примеры, где с is/has начинаются boolean и никто от этого не умер.
https://github.com/airbnb/javascript#comparison--shortcuts
https://github.com/airbnb/javascript#coercion--booleans
https://github.com/airbnb/javascript#properties--dot

2022-06-17 12:57 UTC, ShmidtAlex commented on src/mixins/roles.js
> +export const rolesFactory = (teamIdPath, isDraft) => ({
метод rolesFactory используется много где, это попытка указать, что речь о вызове метода из draftNftItem

2022-06-17 12:59 UTC, ShmidtAlex commented on src/mixins/roles.js
> +        id = this.project.issuedByTeam
там есть проблема в очередности выполнения, если передавать вычисленный id из компонента - он будет всегда undefined

2022-06-17 13:03 UTC, ShmidtAlex commented on src/mixins/roles.js
> +        id = this.project.issuedByTeam
> Если это какая-то особая проверка, то лучше ее делать в компоненте. Или переделать этот метод, чтобы он получал teamId как параметр. А откуда берется эта id, решалось бы в компоненте

тогда уж лучше обойтись без $$isTeamAdmin, прямо на месте и вычислить может пользователь создавать драфт или нет

2022-06-17 13:04 UTC, d-tsaruk commented on src/mixins/roles.js
> +export const rolesFactory = (teamIdPath, isDraft) => ({
я не спорю. Вообще не смертельно, но как раз таки следования некоторым общепринятым принципам нейминга и т д, значительно упрощает понимание кода, особенно в js, где в переменной может лежать как boolean переменная так и функция. И это реально круто когда код читаем и понятен еще на уровне его чтения. без консоль логов и перепроверок.

2022-06-17 13:13 UTC, d-tsaruk commented on src/mixins/roles.js
> +      let id = this[teamIdPath];
окей. а почему тогда let. ты вроде его нигде не меняешь. оставь его const как было

2022-06-17 13:55 UTC, elena-vlasova commented on src/mixins/roles.js
> +export const rolesFactory = (teamIdPath, isDraft) => ({
Каким общепринятым принципам нейминга? 
Погуглила boolean naming convention, ни в одной статье или доке с первой страницы не нашла, что с is может называться только функция, но ни в коем случае не переменная.

2022-06-21 15:05 UTC, elena-vlasova requested changes

2022-06-22 07:53 UTC, elena-vlasova approved these changes

2022-06-22 07:53 UTC, merged